# Generated by Django 4.0.3 on 2022-03-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_posted',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_posted',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_published',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='date_posted',
        ),
    ]
