# Generated by Django 4.0.3 on 2022-03-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_workspace_alter_specialization_name_user_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_specialization',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user_specialization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_workspace',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_workspace',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='user_specialization',
        ),
        migrations.DeleteModel(
            name='user_workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
